import type { MaterialPreset } from './material-types';

const material = (preset: MaterialPreset): MaterialPreset => preset;

export const MATERIAL_PRESETS: MaterialPreset[] = [
  material({ id: 'none', name: 'None', family: 'surface', description: 'No material finish.', safety: 'commercial-safe', defaultStrength: 0, maxSafeStrength: 0, blendMode: 'mask-only', affectsLuma: false, affectsChroma: false, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['clean exports'], avoidFor: [], tags: ['none'] }),
  material({ id: 'cold-press-paper', name: 'Cold Press Paper', family: 'paper', description: 'Soft tooth and fiber variation for art-paper depth.', safety: 'portrait-safe', defaultStrength: 18, maxSafeStrength: 34, blendMode: 'soft-light', affectsLuma: true, affectsChroma: false, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['matte editorial', 'portrait prints'], avoidFor: ['gloss product renders'], tags: ['paper', 'tooth'] }),
  material({ id: 'hot-press-paper', name: 'Hot Press Paper', family: 'paper', description: 'Smoother paper body with restrained micro-fiber.', safety: 'portrait-safe', defaultStrength: 12, maxSafeStrength: 28, blendMode: 'soft-light', affectsLuma: true, affectsChroma: false, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['soft luxury', 'clean portraits'], avoidFor: ['heavy xerox'], tags: ['paper', 'matte'] }),
  material({ id: 'newsprint', name: 'Newsprint', family: 'paper', description: 'Absorbent gray paper base with coarse fiber.', safety: 'graphic-bold', defaultStrength: 38, maxSafeStrength: 70, blendMode: 'multiply', affectsLuma: true, affectsChroma: true, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: true, bestFor: ['editorial print', 'zines'], avoidFor: ['beauty retouch'], tags: ['paper', 'print'] }),
  material({ id: 'magazine-paper', name: 'Magazine Paper', family: 'paper', description: 'Coated editorial stock with light sheen and smooth ink hold.', safety: 'commercial-safe', defaultStrength: 16, maxSafeStrength: 38, blendMode: 'soft-light', affectsLuma: true, affectsChroma: false, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['fashion', 'campaigns'], avoidFor: ['rough copy effects'], tags: ['paper', 'editorial'] }),
  material({ id: 'matte-photo-paper', name: 'Matte Photo Paper', family: 'paper', description: 'Premium matte finish with subdued reflection.', safety: 'portrait-safe', defaultStrength: 12, maxSafeStrength: 26, blendMode: 'soft-light', affectsLuma: true, affectsChroma: false, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['portraits', 'soft luxury'], avoidFor: ['chrome product'], tags: ['matte', 'photo'] }),
  material({ id: 'glossy-photo-paper', name: 'Glossy Photo Paper', family: 'paper', description: 'Polished photo surface with controlled highlight sheen.', safety: 'commercial-safe', defaultStrength: 14, maxSafeStrength: 34, blendMode: 'screen', affectsLuma: true, affectsChroma: false, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['product gloss', 'commercial portraits'], avoidFor: ['flat newsprint'], tags: ['gloss', 'photo'] }),
  material({ id: 'risograph-ink', name: 'Risograph Ink', family: 'print', description: 'Limited-palette ink body with overprint and misregistration.', safety: 'graphic-bold', defaultStrength: 62, maxSafeStrength: 88, blendMode: 'multiply', affectsLuma: true, affectsChroma: true, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: true, bestFor: ['posters', 'editorial graphics'], avoidFor: ['skin-safe beauty'], tags: ['riso', 'ink'] }),
  material({ id: 'screenprint-ink', name: 'Screenprint Ink', family: 'print', description: 'Thicker ink spread and edge gain for apparel-style graphics.', safety: 'graphic-bold', defaultStrength: 58, maxSafeStrength: 86, blendMode: 'multiply', affectsLuma: true, affectsChroma: true, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: true, bestFor: ['streetwear', 'posters'], avoidFor: ['headshots'], tags: ['screenprint', 'ink'] }),
  material({ id: 'toner-xerox', name: 'Toner / Xerox', family: 'print', description: 'Toner speckle, banding, and copy degradation.', safety: 'graphic-bold', defaultStrength: 66, maxSafeStrength: 92, blendMode: 'multiply', affectsLuma: true, affectsChroma: false, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: true, bestFor: ['zines', 'posters'], avoidFor: ['premium beauty'], tags: ['toner', 'xerox'] }),
  material({ id: 'fine-35mm-grain', name: 'Fine 35mm Grain', family: 'film', description: 'Luma-dependent fine emulsion grain integrated into shadows and mids.', safety: 'portrait-safe', defaultStrength: 18, maxSafeStrength: 36, blendMode: 'grain-merge', affectsLuma: true, affectsChroma: true, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['film looks', 'portraits'], avoidFor: ['clean ecommerce'], tags: ['film', 'grain'] }),
  material({ id: 'pushed-35mm-grain', name: 'Pushed 35mm Grain', family: 'film', description: 'Chunkier pushed grain with controlled clumping.', safety: 'commercial-safe', defaultStrength: 32, maxSafeStrength: 58, blendMode: 'grain-merge', affectsLuma: true, affectsChroma: true, affectsEdges: false, affectsSkin: true, supportsPortraitProtection: true, bestFor: ['night film', 'cinematic'], avoidFor: ['beauty closeups'], tags: ['film', 'grain'] }),
  material({ id: 'super-8-emulsion', name: 'Super 8 Emulsion', family: 'film', description: 'Small-gauge grain, gate dust, softness, and vignette character.', safety: 'commercial-safe', defaultStrength: 42, maxSafeStrength: 70, blendMode: 'grain-merge', affectsLuma: true, affectsChroma: true, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: true, bestFor: ['nostalgia', 'motion stills'], avoidFor: ['crisp products'], tags: ['super8', 'film'] }),
  material({ id: 'phone-sensor-noise', name: 'Phone Sensor Noise', family: 'digital', description: 'High-ISO chroma/luma noise with compression-aware restraint.', safety: 'portrait-safe', defaultStrength: 14, maxSafeStrength: 28, blendMode: 'grain-merge', affectsLuma: true, affectsChroma: true, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['night selfies'], avoidFor: ['print simulation'], tags: ['digital', 'sensor'] }),
  material({ id: 'jpeg-compression', name: 'JPEG Compression', family: 'digital', description: 'Block compression and chroma roughness for web artifacts.', safety: 'experimental', defaultStrength: 54, maxSafeStrength: 88, blendMode: 'overlay', affectsLuma: true, affectsChroma: true, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: false, bestFor: ['deep web', 'glitch'], avoidFor: ['client portraits'], tags: ['jpeg', 'compression'] }),
  material({ id: 'crt-phosphor', name: 'CRT Phosphor', family: 'digital', description: 'RGB phosphor striping, scanline density, and screen glow.', safety: 'experimental', defaultStrength: 62, maxSafeStrength: 92, blendMode: 'overlay', affectsLuma: true, affectsChroma: true, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: false, bestFor: ['screens', 'retro tech'], avoidFor: ['skin-safe presets'], tags: ['crt', 'scanline'] }),
  material({ id: 'linen-fiber', name: 'Linen Fiber', family: 'surface', description: 'Fine woven textile tooth for tactile product/editorial surfaces.', safety: 'commercial-safe', defaultStrength: 18, maxSafeStrength: 42, blendMode: 'soft-light', affectsLuma: true, affectsChroma: false, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['food', 'lifestyle product'], avoidFor: ['xerox'], tags: ['linen', 'fiber'] }),
  material({ id: 'canvas-tooth', name: 'Canvas Tooth', family: 'surface', description: 'Visible woven canvas surface with restrained edge disruption.', safety: 'commercial-safe', defaultStrength: 24, maxSafeStrength: 48, blendMode: 'soft-light', affectsLuma: true, affectsChroma: false, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: true, bestFor: ['art prints'], avoidFor: ['beauty headshots'], tags: ['canvas', 'tooth'] }),
  material({ id: 'brushed-metal', name: 'Brushed Metal', family: 'surface', description: 'Directional micro-scratches for metal and chrome product finishes.', safety: 'commercial-safe', defaultStrength: 16, maxSafeStrength: 40, blendMode: 'soft-light', affectsLuma: true, affectsChroma: false, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['chrome', 'product'], avoidFor: ['portraits'], tags: ['metal', 'product'] }),
  material({ id: 'glass-reflection', name: 'Glass Reflection', family: 'surface', description: 'Subtle diagonal reflection and micro-contrast for glossy products.', safety: 'commercial-safe', defaultStrength: 14, maxSafeStrength: 34, blendMode: 'screen', affectsLuma: true, affectsChroma: false, affectsEdges: false, affectsSkin: false, supportsPortraitProtection: true, bestFor: ['glass', 'acrylic', 'skincare'], avoidFor: ['matte paper'], tags: ['glass', 'gloss'] }),
  material({ id: 'bitmap-dither', name: 'Bitmap Dither', family: 'graphic', description: 'Ordered or error-diffusion bitmap conversion with silhouette priority.', safety: 'graphic-bold', defaultStrength: 72, maxSafeStrength: 100, blendMode: 'mask-only', affectsLuma: true, affectsChroma: true, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: true, bestFor: ['streetwear bitmap'], avoidFor: ['portrait safety'], tags: ['bitmap', 'dither'] }),
  material({ id: 'manga-screentone', name: 'Manga Screentone', family: 'graphic', description: 'Tone-dot screen behavior for illustration and manga-inspired prints.', safety: 'graphic-bold', defaultStrength: 64, maxSafeStrength: 92, blendMode: 'multiply', affectsLuma: true, affectsChroma: false, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: true, bestFor: ['manga', 'poster art'], avoidFor: ['commercial product color'], tags: ['manga', 'screentone'] }),
  material({ id: 'thermal-print', name: 'Thermal Print', family: 'graphic', description: 'Thermal-print flattening and heat-like posterization.', safety: 'experimental', defaultStrength: 70, maxSafeStrength: 100, blendMode: 'overlay', affectsLuma: true, affectsChroma: true, affectsEdges: true, affectsSkin: true, supportsPortraitProtection: false, bestFor: ['experimental'], avoidFor: ['portraits'], tags: ['thermal', 'experimental'] })
];

export const MATERIAL_PRESET_MAP = new Map(MATERIAL_PRESETS.map((preset) => [preset.id, preset]));

export const getMaterialPreset = (id: string | null | undefined): MaterialPreset => (
  MATERIAL_PRESET_MAP.get(id ?? 'none') ?? MATERIAL_PRESET_MAP.get('none')!
);
